// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    type, trigger_value, threshold
) VALUES (
    $1, $2, $3
) RETURNING id, timestamp, type, trigger_value, threshold, resolved_at, active
`

type CreateAlertParams struct {
	Type         string
	TriggerValue int32
	Threshold    int32
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert, arg.Type, arg.TriggerValue, arg.Threshold)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Type,
		&i.TriggerValue,
		&i.Threshold,
		&i.ResolvedAt,
		&i.Active,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, timestamp, type, trigger_value, threshold, resolved_at, active FROM alerts WHERE id = $1
`

func (q *Queries) GetAlertByID(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Type,
		&i.TriggerValue,
		&i.Threshold,
		&i.ResolvedAt,
		&i.Active,
	)
	return i, err
}

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT id, timestamp, type, trigger_value, threshold, resolved_at, active FROM alerts WHERE active = true ORDER BY timestamp DESC
`

func (q *Queries) ListActiveAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Type,
			&i.TriggerValue,
			&i.Threshold,
			&i.ResolvedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, timestamp, type, trigger_value, threshold, resolved_at, active FROM alerts ORDER BY timestamp DESC LIMIT $1 OFFSET $2
`

type ListAlertsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Type,
			&i.TriggerValue,
			&i.Threshold,
			&i.ResolvedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts SET active = false, resolved_at = NOW() WHERE id = $1 RETURNING id, timestamp, type, trigger_value, threshold, resolved_at, active
`

func (q *Queries) ResolveAlert(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Type,
		&i.TriggerValue,
		&i.Threshold,
		&i.ResolvedAt,
		&i.Active,
	)
	return i, err
}
