// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID           pgtype.UUID
	Timestamp    pgtype.Timestamptz
	Type         string
	TriggerValue int32
	Threshold    int32
	ResolvedAt   pgtype.Timestamptz
	Active       bool
}

type SensorReading struct {
	ID            pgtype.UUID
	Timestamp     pgtype.Timestamptz
	GasValue      int32
	HumidityValue int32
	DistanceCm    float64
	ObjectCount   int32
	BeltRunning   bool
	FanOn         bool
	BuzzerOn      bool
	DoorAngle     int32
}
