// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: readings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReading = `-- name: CreateReading :one
INSERT INTO sensor_readings (
    gas_value, humidity_value, distance_cm, object_count,
    belt_running, fan_on, buzzer_on, door_angle
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, timestamp, gas_value, humidity_value, distance_cm, object_count, belt_running, fan_on, buzzer_on, door_angle
`

type CreateReadingParams struct {
	GasValue      int32
	HumidityValue int32
	DistanceCm    float64
	ObjectCount   int32
	BeltRunning   bool
	FanOn         bool
	BuzzerOn      bool
	DoorAngle     int32
}

func (q *Queries) CreateReading(ctx context.Context, arg CreateReadingParams) (SensorReading, error) {
	row := q.db.QueryRow(ctx, createReading,
		arg.GasValue,
		arg.HumidityValue,
		arg.DistanceCm,
		arg.ObjectCount,
		arg.BeltRunning,
		arg.FanOn,
		arg.BuzzerOn,
		arg.DoorAngle,
	)
	var i SensorReading
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.GasValue,
		&i.HumidityValue,
		&i.DistanceCm,
		&i.ObjectCount,
		&i.BeltRunning,
		&i.FanOn,
		&i.BuzzerOn,
		&i.DoorAngle,
	)
	return i, err
}

const getLatestReading = `-- name: GetLatestReading :one
SELECT id, timestamp, gas_value, humidity_value, distance_cm, object_count, belt_running, fan_on, buzzer_on, door_angle FROM sensor_readings ORDER BY timestamp DESC LIMIT 1
`

func (q *Queries) GetLatestReading(ctx context.Context) (SensorReading, error) {
	row := q.db.QueryRow(ctx, getLatestReading)
	var i SensorReading
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.GasValue,
		&i.HumidityValue,
		&i.DistanceCm,
		&i.ObjectCount,
		&i.BeltRunning,
		&i.FanOn,
		&i.BuzzerOn,
		&i.DoorAngle,
	)
	return i, err
}

const getReadingByID = `-- name: GetReadingByID :one
SELECT id, timestamp, gas_value, humidity_value, distance_cm, object_count, belt_running, fan_on, buzzer_on, door_angle FROM sensor_readings WHERE id = $1
`

func (q *Queries) GetReadingByID(ctx context.Context, id pgtype.UUID) (SensorReading, error) {
	row := q.db.QueryRow(ctx, getReadingByID, id)
	var i SensorReading
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.GasValue,
		&i.HumidityValue,
		&i.DistanceCm,
		&i.ObjectCount,
		&i.BeltRunning,
		&i.FanOn,
		&i.BuzzerOn,
		&i.DoorAngle,
	)
	return i, err
}

const listReadings = `-- name: ListReadings :many
SELECT id, timestamp, gas_value, humidity_value, distance_cm, object_count, belt_running, fan_on, buzzer_on, door_angle FROM sensor_readings ORDER BY timestamp DESC LIMIT $1 OFFSET $2
`

type ListReadingsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListReadings(ctx context.Context, arg ListReadingsParams) ([]SensorReading, error) {
	rows, err := q.db.Query(ctx, listReadings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.GasValue,
			&i.HumidityValue,
			&i.DistanceCm,
			&i.ObjectCount,
			&i.BeltRunning,
			&i.FanOn,
			&i.BuzzerOn,
			&i.DoorAngle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingsSince = `-- name: ListReadingsSince :many
SELECT id, timestamp, gas_value, humidity_value, distance_cm, object_count, belt_running, fan_on, buzzer_on, door_angle FROM sensor_readings WHERE timestamp > $1 ORDER BY timestamp DESC
`

func (q *Queries) ListReadingsSince(ctx context.Context, timestamp pgtype.Timestamptz) ([]SensorReading, error) {
	rows, err := q.db.Query(ctx, listReadingsSince, timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.GasValue,
			&i.HumidityValue,
			&i.DistanceCm,
			&i.ObjectCount,
			&i.BeltRunning,
			&i.FanOn,
			&i.BuzzerOn,
			&i.DoorAngle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
