// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSystemStatus = `-- name: GetSystemStatus :many
WITH latest_reading AS (
    SELECT id, timestamp, gas_value, humidity_value, distance_cm, object_count, belt_running, fan_on, buzzer_on, door_angle FROM sensor_readings ORDER BY timestamp DESC LIMIT 1
),
active_alerts_count AS (
    SELECT count(*) AS total FROM alerts WHERE active = true
)
SELECT
    l.timestamp AS last_seen,
    l.belt_running,
    l.fan_on,
    l.buzzer_on,
    l.door_angle,
    COALESCE((SELECT sum(object_count) FROM sensor_readings), 0)::bigint AS object_count_total,
    COALESCE(aac.total, 0)::int AS active_alerts
FROM latest_reading l
CROSS JOIN active_alerts_count aac
`

type GetSystemStatusRow struct {
	LastSeen         pgtype.Timestamptz
	BeltRunning      bool
	FanOn            bool
	BuzzerOn         bool
	DoorAngle        int32
	ObjectCountTotal int64
	ActiveAlerts     int32
}

func (q *Queries) GetSystemStatus(ctx context.Context) ([]GetSystemStatusRow, error) {
	rows, err := q.db.Query(ctx, getSystemStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSystemStatusRow
	for rows.Next() {
		var i GetSystemStatusRow
		if err := rows.Scan(
			&i.LastSeen,
			&i.BeltRunning,
			&i.FanOn,
			&i.BuzzerOn,
			&i.DoorAngle,
			&i.ObjectCountTotal,
			&i.ActiveAlerts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
